---
- name: Install apache2
  apt:
    name: '{{ item }}'
    update_cache: yes
  with_items:
    - apache2
    - apache2-utils

- name: Add ServerName directive
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: ServerName
    line: 'ServerName {{ ldap_server_ip }}'
  notify: restart apache2
