---
- name: Install ldap
  apt:
    name: '{{ item }}'
  with_items:
    - slapd
    - ldap-utils

# Using ufw module gives me "ERROR: Could not find a profile matching 'ldap'\n"
- name: Open up the LDAP port on firewall so external clients can connect
  command: ufw allow ldap

- name: Install phpldapadmin
  apt:
    name: phpldapadmin

- name: Configure phpldapadmin
  copy:
    src: config.php
    dest: /etc/phpldapadmin/config.php
