---
- name: Install necessary LDAP client packages
  apt:
    name: '{{ item }}'
  with_items:
    - libnss-ldap
    - libpam-ldap
    - ldap-utils
    - nscd

- name: Configure ldap conf
  template:
    src: ldap.conf.j2
    dest: /etc/ldap.conf
  notify: restart nscd

- name: Configure nsswitch.conf to work with LDAP
  copy:
    src: nsswitch.conf
    dest: /etc/nsswitch.conf
  notify: restart nscd

- name: Enable home directory to be created automatically
  copy:
    src: common-session
    dest: /etc/pam.d/common-session
  notify: restart nscd
